{
  "formatVersion": "1.1",
  "component": {
    "group": "io.webpkit",
    "module": "player",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "player-1.0.2.aar",
          "url": "player-1.0.2.aar",
          "size": 497587,
          "sha512": "20a69ab07e58be52409b15187275367327a7025396361f17b9fd584760fb512f3b8f2045b892fa03af817ea385013c1e2f0538b5bc963e91f236b202f2ec8339",
          "sha256": "7b5619fd1616e88f3307d91dcb52f8ce6e793cee593028e7a49c07a986462d72",
          "sha1": "e9ed9a95ec34cda7bce3db0719c5da1882732575",
          "md5": "d9fd8af393fde49c9340e2eb09e9837d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "player-1.0.2.aar",
          "url": "player-1.0.2.aar",
          "size": 497587,
          "sha512": "20a69ab07e58be52409b15187275367327a7025396361f17b9fd584760fb512f3b8f2045b892fa03af817ea385013c1e2f0538b5bc963e91f236b202f2ec8339",
          "sha256": "7b5619fd1616e88f3307d91dcb52f8ce6e793cee593028e7a49c07a986462d72",
          "sha1": "e9ed9a95ec34cda7bce3db0719c5da1882732575",
          "md5": "d9fd8af393fde49c9340e2eb09e9837d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "player-1.0.2-sources.jar",
          "url": "player-1.0.2-sources.jar",
          "size": 37723,
          "sha512": "431d9cf5165f1937326515e0a2c967fcfb875fea93a16dd5a9d645b3a382c83e7cc0cb5231f7cda8f10ed61614cc24cde9650f4384132fbcf1f64cbf3e564cd0",
          "sha256": "871ed6375e2d8a577161003aae9d40c76819101dd9241798b4d3afd1b882381b",
          "sha1": "de8137b0afb703df23a076451145d351c1b6c0ee",
          "md5": "58f13872bdbd502b62c48cace82cc5b6"
        }
      ]
    }
  ]
}
